### ISSUE TITLE
USWDS-Compile - Sass: Quiet Sass deprecation warnings

### ISSUE THREAD

**Issue by mahoneycm** [uswds/uswds-compile#132]
# Description

After #126, Sass released new minor versions which brought on additional Sass deprecations.

## Problem statement

Downstream users are alerted about upcoming Sass deprecations that aren't yet deprecated and are out of their control. 

## Proposed solution

Since we are aware of the upcoming deprecations and are working towards fixing them. We should silence the deprecations, but give the users the option to turn he warning messages back on.

**Comment by mejiaj** [comment]
@mahoneycm updated the title for clarity.
