### ISSUE TITLE
Why use functions instead of gulp task

### ISSUE THREAD

**Issue by smustgrave** [uswds/uswds-compile#21]
Curious as to why the functions aren't gulp tasks in the traditional way?

**Comment by mejiaj** [comment]
Morning! When gulp v4 came out they recommended using function definitions in their [guidance](https://gulpjs.com/docs/en/getting-started/creating-tasks).

IMO this setup is more straightforward and allows us to reuse tasks in a cleaner way.

**Comment by smustgrave** [comment]
Gotcha was curious.  Thanks for answering!
