### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by smustgrave** [uswds/uswds-compile#29]
Trying to use uswds 3.0 and confused on the proper way to update?

We output the scss files to a directory but if you run init again any changes will be erased

**Comment by smustgrave** [comment]
Can close as a duplicate of https://github.com/uswds/uswds-compile/issues/19

**Comment by thisisdano** [comment]
For most projects, you can follow the [Migration Guidance](https://designsystem.digital.gov/documentation/migration/) on our website. There are `uswds-compile`–specific instructions on that page as well: https://designsystem.digital.gov/documentation/migration/#3-update-your-sass-compiler-settings-and-recompile-css

**Comment by thisisdano** [comment]
I'll follow up on the specific issue in #19 in that issue.
