### ISSUE TITLE
USWDS-Compile - Feature: Allow disabling sourcemaps

### ISSUE THREAD

**Issue by rayestrada** [uswds/uswds-compile#70]
### Is your feature request related to a problem? Please describe.

When using this tool in our USWDS + Drupal + static site generation setup the .map sourcemap files aren't copied over because they are comments in the css and not actual source file references. This causes the .map files to be listed as missing in the console. If we can conditionally disable sourcemaps as an option then we would not have missing files in the console log.

### Describe the solution you'd like

Add an option to disable sourcemaps in the output css.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-compile/issues) for duplicate feature requests.

**Comment by amyleadem** [comment]
Moving this issue back into "Review" status while we investigate [the issue](https://github.com/uswds/uswds-compile/pull/103#issuecomment-2229199140) flagged in PR #103.

**Comment by amyleadem** [comment]
Moving this back into "Fed final" since we have a proposed fix in #110
