### ISSUE TITLE
USWDS-Compile - Bug:  uswds-compile stopped compiling CSS

### ISSUE THREAD

**Issue by ryandwalker** [uswds/uswds-compile#95]
### Describe the bug

In the past week, uswds-compile stopped working.  My CSS no longer reflects any changes to my SCSS after I run `npx gulp compile`.  The last-updated date on the CSS file changes, but its contents do not change.  

Just now I upgraded from uswds-compile 1.0 to 1.1.0, but this did not resolve the problem.

The uswds-compile package was working without incident for three months prior to this issue.

### Steps to reproduce the bug

Run `npx gulp compile` and inspect the CSS for changes.  It does not reflect the changes made in my SCSS file.

### Expected Behavior

I expect the CSS to reflect the changes to my SCSS after I compile.

### System setup

"@uswds/compile": "^1.1.0"

"@uswds/uswds": "3.7.0"

The web server is IIS.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-compile/issues) for duplicate bug reports.

**Comment by ryandwalker** [comment]
I upgraded to USWDS 3.8.0 just now but this did not resolve the issue.

**Comment by mejiaj** [comment]
Hey @ryandwalker, sorry to hear about the issues. To help debug this, would you be able to provide:

1. The version of Node you're using
2. A sample of your gulpfile
3. Are you seeing any log errors or messages in general when running the task?
4. To confirm, do you run the `npx gulp compile` command in powershell on your windows machine?

Admittedly, it's been a while since I've worked on a windows machine —  but if you can provide more information that will help us out a lot.

**Comment by ryandwalker** [comment]
$ node -v
v20.2.0

gulpfile.js:  

/* gulpfile.js */

const uswds = require("@uswds/compile");

/**
 * USWDS version
 */

uswds.settings.version = 3;

/**
 * Path settings
 * Set as many as you need
 */

uswds.paths.dist.css = './css';
uswds.paths.dist.theme = './sass';

/**
 * Exports
 * Add as many as you need
 */

exports.init = uswds.init;
exports.compile = uswds.compile;
exports.watch = uswds.watch;

I see no errors.  Please see attached gulp-compile-output.txt.
[gulp-compile-output.txt](https://github.com/uswds/uswds-compile/files/14836284/gulp-compile-output.txt)

I use Windows Terminal:  https://apps.microsoft.com/detail/9n0dx20hk701?hl=en-US&gl=US

**Comment by ryandwalker** [comment]
I am no longer sure there is any problem with the compiling.  I think I might be facing some other issue.  I'm going to close this bug report for now.
